name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Lint
      uses: mooyoul/tslint-actions@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '*.ts'      
    - name: bazel build
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: build //...
