name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      
    - name: bazel build
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: build //...
